---
keys:
  - &gwen age1yx86m88mcvpq2z069cj5a37hgmwnlpv4tzsk2ndya6equ0ra2gsq938vde
  - &mithrix age1sklfnht5lgc9psmrzrujapfhyclzc72argvk4hya67u3cdtag58smg0vhq
creation_rules:
  - path_regex: secrets/gwen/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *gwen
  - path_regex: secrets/aurelionite/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *gwen
  - path_regex: secrets/grovetender/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *gwen
  - path_regex: secrets/mithrix/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *mithrix
