hello: ENC[AES256_GCM,data:v9ShGOHdmW2Ya4sWBsbrQf1QLb04g6iUoWYK24N3ZoREGFPkNsPax3iAIhPIUZo=,iv:1mX81H6ot5Rr5scHgfFLLku04DsPqXOcyllTIzkuQmI=,tag:QpI1KpdZ6c4i+QtpNJIo/w==,type:str]
#ENC[AES256_GCM,data:RObefUtA21ylJre/6LTy6+DVRX2kOZ0nJA3/VQzA,iv:jm11SdQjDsiWQlj8NfWV4yZKg3MjRfeNKKaFj6wDjDY=,tag:qRwG2w7oLNVZhXkPx2Wf3A==,type:comment]
gwen-password: ENC[AES256_GCM,data:foVLP78R,iv:dx0H6x2F/kJNyJpcZkHYdIdUfiUZt8tJRdTpG4CavCo=,tag:NXMEGkrW1A1IeSqJni2Ryw==,type:int]
#ENC[AES256_GCM,data:unBGeH0moQAXvL0NyiiVsQ==,iv:Ixp/KChtYB+/SQrK7CgNuVp2vFM3lG+tGQq05f+Elb8=,tag:/yWmswerGqXrDHArq6mKNA==,type:comment]
gmail-gkerno-password: ENC[AES256_GCM,data:u9T9QQLfXdoS22M/EpE0WfMZ5mTj1f417tDLkv3kx0q48eZs,iv:101bwbQO3y6CbX/rBLusUryQfM5HYMheTvtO/W9rkMg=,tag:TAhW1FMBN8dARLWqyvT7pA==,type:str]
gmail-gwenchlan-password: ENC[AES256_GCM,data:dTeEAAm9Wk/zXz+pVWeUBosXz5n7K/7tklBu4Mpk4F0weyHe,iv:aHp7dThFgUgWVsdXZWLfWmUpZ1kCugsnlgKMFiR12vE=,tag:oJQfgfklBlBtIiZtnHq97g==,type:str]
spotify-password: ENC[AES256_GCM,data:dA7ilHjq6y5NVPB1h1hI,iv:roz8t9utCkVljI/dA++wl9Ga98aFRCkk7qgSvdx0ITA=,tag:84sWG520ZrzJbFKDJHcu1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7ng7jxyt0pmtwqvcfyungn6n6yzzmg289xfhusmj6z2hdwktylslv9lhz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOUZNUFJ3NFM5ZmNFWXhT
            MEpXM25LRmg2TFV0cjJENm84MFF3NUFoRUFFClQ2OWtmSGw5MlNuQXl3c3lKNEsw
            OUkvOERsaVRaSGpZRVdiU09nc3A4aEEKLS0tIGxCVm1ib2ZvWDBLaGpWTDgxUWky
            MlA0MEl1cGhheE5uU3hzZ1pKK2dnRnMKKJTOkDSKpFEo7uFyNB55wA4lCrRrTj4j
            zlB+YzjlRHMeo/pkvZ9D+S0JkSG5RQMc4xS0PBlzeuh5K43n56g2pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-27T19:04:16Z"
    mac: ENC[AES256_GCM,data:kjeGL2Dp9P+3X6QQsqM3tIcMzAqUN/xwNB7UFzmDdbH4Sv0caGcxeuHPmYbG9sPX0x0tjgTzLfFMAZaD6gW+bKd1+d6drzJiGiMQA5MAe47UJXS2cmbuZlxkhn2RVP32UpBuse+v8hFu6Mil9uKcV3aiHeqYt8c/Bf0L72auHt8=,iv:vEfCXLMqihco2d+5cD0m3wKa4qXktWpaHg44wTEBFik=,tag:/qH11jfsTDb11TPG8ajtzA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
